### ISSUE TITLE
The app is not working at all

### ISSUE THREAD

**Issue by J053Fabi0** [ianmcxa/vortaro#11]
When I open the app (downloaded from F-Droid) it only shows a blank screen with a green tab at the top. The only thing that works is the About menu.

![Screenshot_20210107-083728_Senreta_Vortaro](https://user-images.githubusercontent.com/12930717/103899698-62682c00-50bc-11eb-8295-56e2a97dcb6e.png)

**Comment by thebiblelover7** [comment]
@wildeyedskies Do you know anything about this? I'm having the same issue.

**Comment by wildeyedskies** [comment]
If you click on the title bar it should bring up the keyboard. Does that happen? Also can you tell me what android device and version you are on.

**Comment by thebiblelover7** [comment]
@wildeyedskies Now it works, I didn't know how it worked, now I do. Thanks!
