### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by nicolasmaia** [ianmcxa/vortaro#3]
Hey I just downloaded it from F-Droid and as soon as I type anything into the search box, the app crashes.

**Comment by ianmcxa** [comment]
What device/android version were you using? If possible, can you send a logcat log?

**Comment by nicolasmaia** [comment]
I'm temporarily without it, but it's Android 4.4. I'll look into logcat soon when I get it back.

**Comment by nicolasmaia** [comment]
I no longer have that device so I can't reproduce it. I'm using a newer Android device and not having problems. Closing now.
