### ISSUE TITLE
Google Play version is ahead of Github and F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [ianmcxa/vortaro#6]
Why is that? I was going to ask F-Droid to update Senreta Vortaro but apparently the last release here was indeed 0.2.

**Comment by ianmcxa** [comment]
F-Droid is managed on Gitlab, I don't have much insight into how they do updates.

**Comment by picsi** [comment]
@rudloff can perhaps help here

**Comment by ianmcxa** [comment]
I was under the impression that the F-Droid build system should pick up my updates automatically.

**Comment by thermatk** [comment]
@ianmcxa you would be right, but you didn't tag a recent release, so nothing to pick up
just tag and it will be resolved

**Comment by ianmcxa** [comment]
Alright, I've created a new tag, so hopefully that does it.

**Comment by nicolasmaia** [comment]
not sure why it wasn't updated yet, so I opened a ticket in their tracker https://gitlab.com/fdroid/fdroiddata/issues/1242
